# configuration for training market1501

dataset:
    name: market1501

aug:
    resize_size: [256, 128]
    random_mirror: True
    pad: 10
    random_crop: True

test:
    batch_size: 1

network:
    name: 'Baseline'
    last_stride: 1
    gpus: '0'

